# Generated by Django 4.1.1 on 2022-09-13 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituto_ls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_iframe', models.TextField(blank=True, null=True, verbose_name='iFrame de Video')),
                ('image_iframe', models.TextField(blank=True, null=True, verbose_name='iFrame de Imagem')),
                ('index', models.IntegerField()),
            ],
            options={
                'ordering': ['-index'],
            },
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Nome')),
                ('cover', models.URLField(verbose_name='Foto (fundo transparente)')),
                ('bio', models.TextField(max_length=150, verbose_name='Biografia suscinta')),
            ],
        ),
    ]
