# Generated by Django 4.1.1 on 2022-09-14 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituto_ls', '0002_feedback_hero'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={},
        ),
        migrations.AlterModelOptions(
            name='hero',
            options={'verbose_name_plural': 'Herois'},
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='index',
        ),
        migrations.AlterField(
            model_name='hero',
            name='cover',
            field=models.URLField(verbose_name='URL da Foto (fundo transparente)'),
        ),
    ]
