# Generated by Django 4.1.1 on 2022-09-15 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituto_ls', '0003_alter_feedback_options_alter_hero_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='cover',
            field=models.ImageField(upload_to='', verbose_name='Foto com fundo transparente'),
        ),
    ]
