# Generated by Django 4.1.1 on 2022-09-15 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituto_ls', '0005_alter_hero_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='cover',
            field=models.ImageField(upload_to='hero/', verbose_name='Foto com fundo transparente'),
        ),
    ]
