# Generated by Django 4.1.1 on 2022-09-15 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituto_ls', '0006_alter_hero_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='cover',
            field=models.ImageField(upload_to='hero', verbose_name='Foto com fundo transparente'),
        ),
    ]
