# Generated by Django 4.1.1 on 2022-09-15 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituto_ls', '0007_alter_hero_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='cover_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL da imagem'),
        ),
    ]
