# Generated by Django 4.1.1 on 2022-09-16 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instituto_ls', '0009_alter_hero_cover_url_alter_product_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='cover_url',
        ),
    ]
